### ISSUE TITLE
data.filter.ini is ingored

### ISSUE THREAD

**Issue by itcbchris** [pdir/maklermodul-bundle#1]
Module ignores parameter in data.filter.ini 

The file is created under : files/maklermodul/data.filter.ini like described in 

https://docs.maklermodul.de/typen_der_objekteigenschaften.html

with these parameter in it

flaechen.wohnflaeche = 'cssMapRange50'
preise.kaufpreis = 'cssMapRange100000'

new index ist generated but the filter doesnt apply to this settings.

kindly
chris

**Comment by MDevster** [comment]
fixed in 2.0.0
