### ISSUE TITLE
Import via contao-console fails

### ISSUE THREAD

**Issue by itcbchris** [pdir/maklermodul-bundle#10]
I tried to add Cronjob and tested it before into console:

php 7.1 vendor/bin/contao-console maklermodul

Output:  Command "maklermodul" is not defined.

Contao Version:  Version 4.6.14

**Comment by Xendiadyon** [comment]
please try 
`php vendor/bin/contao-console maklermodul:import`

the usage of `php 7.1` as alias of php in the version 7.1 does not seem a correct command for php.
Which hoster do you use?
What is the output of `php 7.1 -v`?

**Comment by itcbchris** [comment]
Is hosted by alfahosting.

  Christian Methfessel <notifications@github.com> hat am 13. August 2019 um 15:25 geschrieben:
 
 
 please try php vendor/bin/contao-console maklermodul:import 
 the usage of php 7.1 does not seem a correct command for php. Which hoster do you use?

**Comment by MDevster** [comment]
Please test
**/usr/bin/php7.1 vendor/bin/contao-console maklermodul:import**
in your root folder of contao installation instead of 
php vendor/bin/contao-console maklermodul:import

PHP-path for alfahosting: /usr/bin/php{major}.{minor}

**Comment by MDevster** [comment]
Please update to latest version, we also add a sync command to run import and sync with one command.
