### ISSUE TITLE
data.filter.ini is not processed when building index by cronjob

### ISSUE THREAD

**Issue by Xendiadyon** [pdir/maklermodul-bundle#11]
## Bug description
In files/maklermodul/data.filter.ini, we chose that the rooms should be displayed as numbers, not as ranges:
`flaechen.anzahl_zimmer = 'cssMapDefault'`

This works correctly, when building the index over the Contao backend.
When using the command
`php7-73LATEST-CLI vendor/bin/contao-console maklermodul:index`
(by command line or cronjob)
the data.filter.ini is ignored

## Steps to reproduce
Probably the data.filter.ini path is not set correctly by using the maklermodul:index command in the contao-console

## Expected behavior
The data.filter.ini should be processed every index-Builtup

## Screenshots
![image](https://user-images.githubusercontent.com/2657385/62944985-1a1cdf80-bdde-11e9-88f3-d785d6ec44d6.png)

## Environment
Contao 4.4 LTS, PHP 7.3, MaklerModul 2.1.4

**Comment by seibtph** [comment]
fixed in new version
