### ISSUE TITLE
filter only clickable once with "Filtertyp UND" in list module

### ISSUE THREAD

**Issue by peerlight** [pdir/maklermodul-bundle#15]
## Bug description
filtering in list view does not work as expected

## Steps to reproduce
- have "Filtertyp UND" in selected in list module (filter buttons)
- view list
- click a filter (region) -> list is filtered 
- re-click filter -> list is expanded again
=> clicking any of this region filter buttons or any filter button of other filter does not do anything

clicking "reset filter" does not help

## Expected behavior
clicking filter buttons should filter list

## Environment
- PHP 7.3
- Contao 4.9.5 (language of site is "de", fallback active)
- pdir/maklermodul-bundle 2.6.4
- pdir/maklermodul-sync-bundle 2.5.3

**Comment by MDevster** [comment]
Please update to the latest version of the modules.
