### ISSUE TITLE
`flaechen.anzahl_zimmer = 'cssMapDefault'` crashes filter

### ISSUE THREAD

**Issue by peerlight** [pdir/maklermodul-bundle#16]
## Bug description
Using `flaechen.anzahl_zimmer = 'cssMapDefault'` in data.filter.ini makes filter not working

## Steps to reproduce
- have working filter with `flaechen.anzahl_zimmer = 'cssMapRange1'`  leading to 
`<button class="button mm-filter-btn " data-filter=".flaechen-anzahl-zimmer-2-3"> 2-3 </button>` 
and 
`<a href=".../expose/..." class="estate geo-regionaler-zusatz-weida flaechen-anzahl-zimmer-2-3 flaechen-wohnflaeche-40-50 preise-warmmiete-300-400 page1" ...>`
- change to `flaechen.anzahl_zimmer = 'cssMapDefault'` in data.filter.ini at /files/maklermodul/data.filter.ini
- result is that data-filter does not correspond to CSS class any more due to "id" in filter name, compare 
`<button class="button mm-filter-btn" data-filter=".flaechen-anzahl-zimmer-id-2">2</button>` 
to 
`<a href=".../expose/..." class="estate geo-regionaler-zusatz-weida flaechen-anzahl-zimmer-2 flaechen-wohnflaeche-40-50 preise-warmmiete-300-400 page1" ...>`

## Expected behavior
Using documented feature should work: https://pdir.de/docs/de/contao/extensions/maklermodul/customization/listview/typen_der_objekteigenschaften/

BTW: Reason for this change is that using a range "2-3 rooms" leads the visitor to expecting flats with 2 AND 3 rooms in the listing. 

## Environment
- PHP 7.3
- Contao 4.9.5 (language of site is "de", fallback active)
- pdir/maklermodul-bundle 2.6.4
- pdir/maklermodul-sync-bundle 2.5.3

**Comment by seibtph** [comment]
If you have created the data.filter.ini you should rebuild the index in the maklermodul setup page. Than it should work.

**Comment by peerlight** [comment]
No. Recreating index does not help. Did this serveral times during investigation including reimport and cache clearing

Test without own data.filter.ini -> no problem

Test with own data.filter.ini AND REINDEXING -> data-filter=".flaechen-anzahl-zimmer-id-2" has "id" in it an can not work with class "flaechen-anzahl-zimmer-2" in estate. 

There seems to be something broken in interpreting the room count as id not as text/string during indexing. Whats the reason for "-id-" being in date-filter?
