### ISSUE TITLE
Error exception when rebuilding Index (maklermodul-sync-bundle)

### ISSUE THREAD

**Issue by grusch-it** [pdir/maklermodul-bundle#18]
## Bug description

Index cannot be built if full import is performed.

An exception with the following message will be thrown:

```
Warning: unlink(path/to/contao/files/maklermodul/data/00index-1606747739-5-00001.json): No such file or directory
```

## Steps to reproduce

1. Run a full import (XML: `uebertragung ⇾ umfang = VOLL`) or use *empty data folder* function
2. Rebuild index

## Expected behavior

The index should be built without any errors.

## Environment

* PHP 7.4
* Contao 4.10
* Maklermodul 2.6.4
* MaklermodulSync 2.5.3

## Possible Fix

`maklermodul-sync-bundle/src/Classes/Service/ImportService.php:292`:

```php
unlink($storageFolder.\DIRECTORY_SEPARATOR.$config->getStorageFileUri());
```

should be replaced by:

```php
if (file_exists($storageFolder.\DIRECTORY_SEPARATOR.$config->getStorageFileUri())) {
    unlink($storageFolder.\DIRECTORY_SEPARATOR.$config->getStorageFileUri());
}
```

If a full import is performed, all directories and files inside the `data` folder will be removed, including all index json files. Thats why an exception will be thrown after trying to rebuild the index after a full import. Because the import service tries to delete the index json files that do not exist (anymore).

**Comment by MDevster** [comment]
fixed in maklermodul 2.7.0 and maklermodul-sync 2.6.0
