### ISSUE TITLE
contao manager and backend show different versions

### ISSUE THREAD

**Issue by peerlight** [pdir/maklermodul-bundle#19]
## Bug description
contao manager and backend show different versions

## Steps to reproduce
look into contao manager and backend

## Expected behavior
ensure correct versions

## Screenshots
![Bildschirmfoto 2020-12-01 um 12 15 02](https://user-images.githubusercontent.com/50866743/100734209-98383780-33cf-11eb-982b-68938abc34d3.png)
![Bildschirmfoto 2020-12-01 um 12 15 15](https://user-images.githubusercontent.com/50866743/100734212-98d0ce00-33cf-11eb-8faf-e98eb61545ab.png)

## Environment
PHP 7.3
Contao 4.9.9
maklermodul 2.6.5
maklermodul-sync 2.5.3

**Comment by MDevster** [comment]
fixed in maklermodul 2.7.0 and maklermodul-sync 2.6.0
