### ISSUE TITLE
insert tags will not replaced on every detail page

### ISSUE THREAD

**Issue by itcbchris** [pdir/maklermodul-bundle#2]
On some Detailpages Contao insert tiges like {{insert_article::..}}, {{date::} and so will not be replaced.

I thought it only appears on pages with special characters in der title / url but it will also appear on other pages.

kindly

**Comment by MDevster** [comment]
Hallo @itcbchris, wir konnten das Verhalten in unser Testversionen Contao 4.4, 4.5 und 4.6 nicht nachstellen. Kannst du uns bitte an **support [at] pdir [punkt] de** einen Zugang zu deiner Installation zusenden?
Als Betreff kannst du gern "Github Issue #2" verwenden.
