### ISSUE TITLE
fresh Install on Contao 4.9.12 not usable

### ISSUE THREAD

**Issue by patcash77** [pdir/maklermodul-bundle#20]
## Bug description
a click on every link in the "Maklermodul"-tab gives the following error :
Call to private Pdir\MaklermodulBundle\Module\MaklermodulSetup::__construct() from context 'Contao\Backend'

a click on "new" gives the following error :
An exception occurred while executing 'INSERT INTO tl_makler (`visible`, `lastUpdate`, `tstamp`) VALUES (1, 1, 0)': SQLSTATE[HY000]: General error: 1364 Field 'anid' doesn't have a default value

The error with the database can be fixed if i give the default value "NULL" to a few fields.

## Steps to reproduce
Did a fresh install and database update with Contao-Manager and tried to use the links in the "Maklermodul"-Tab at the contao-backend

## Environment
apache 2, php7.4-fpm, contao 4.9.12

**Comment by MDevster** [comment]
fixed in version 2.7.4
