### ISSUE TITLE
Probleme beim manuellen Import von Immobilienobjekten

### ISSUE THREAD

**Issue by avoca77** [pdir/maklermodul-bundle#21]
## Bug description
Nach dem manuellen Import der Objekte erhalte ich folgende Fehlermeldung:
`"Internal Server Error
Was ist das Problem?
Call to a member function __toString() on null"`

Die Meldung in der Log-Datei sieht dann wie folgt aus: 
`[2021-03-17 15:13:11] request.INFO: Matched route "contao_backend". {"route":"contao_backend","route_parameters":{"_route":"contao_backend","_scope":"backend","_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\BackendController::mainAction"},"request_uri":"https://example.com//contao?act=import&do=maklermodulSetup&ref=xxxxx","method":"GET"} []
[2021-03-17 15:13:11] request.CRITICAL: Uncaught PHP Exception Error: "Call to a member function __toString() on null" at /www/htdocs/xxxxxxx/verzeichnis/website/c4.9/vendor/pdir/maklermodul-sync-bundle/src/Classes/Domain/Model/ImportTarget.php line 327 {"exception":"[object] (Error(code: 0): Call to a member function __toString() on null at /www/htdocs/xxxxxxx/verzeichnis/website/c4.9/vendor/pdir/maklermodul-sync-bundle/src/Classes/Domain/Model/ImportTarget.php:327)"} []`

Die composer.json wie folgt: 
{
    "type": "project",
    "require": {
        "contao-themes-net/mate-theme-bundle": "^2.12",
        "contao/calendar-bundle": "4.9.*",
        "contao/comments-bundle": "4.9.*",
        "contao/conflicts": "*@dev",
        "contao/faq-bundle": "4.9.*",
        "contao/listing-bundle": "4.9.*",
        "contao/manager-bundle": "4.9.*",
        "contao/news-bundle": "4.9.*",
        "contao/newsletter-bundle": "4.9.*",
        "do-while/contao-backupdb-bundle": "^1.4",
        "inspiredminds/contao-wowjs": "^1.1",
        "madeyourday/contao-rocksolid-columns": "^2.0",
        "madeyourday/contao-rocksolid-custom-elements": "^2.2",
        "madeyourday/contao-rocksolid-slider": "^2.0",
        "pdir/maklermodul-bundle": "^2.7",
        "pdir/maklermodul-sync-bundle": "^2.6",
        "trilobit-gmbh/contao-tiles-bundle": "^1.0"
    },
    "extra": {
        "contao-component-dir": "assets"
    },
    "scripts": {
        "post-install-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ],
        "post-update-cmd": [
            "Contao\\ManagerBundle\\Composer\\ScriptHandler::initializeApplication"
        ]
   },
    "repositories": [
        {
            "type": "composer",
            "url": "https://example.com:xxxxxx@packages.contao.store"
        }
    ]
}

Die Contao-Installation befindet sich im Moment im geschützten Verzeichnis auf einer Testdomain. Die Testdomain ist nicht identisch mit der beim Kauf der Lizenz angegebenen. Könnte dadurch das Problem verursacht worden sein? Die Importdatei stammt aus estateOffice.

## Environment
Contao 4.9.12
maklermodul-bundle: 2.7.4
maklermodul-sync-bundle: 2.6.0
PHP 7.4.14

**Comment by MDevster** [comment]
Die Testdomain ist nicht das Problem. Bitte Zugangsdaten zum Textsystem an support@pdir.de senden und auf diese Ticket verweisen.

**Comment by MDevster** [comment]
fixed in maklermodul-sync-bundle: 2.6.2
