### ISSUE TITLE
Nach Installation der Extension Quelltexteditor defekt

### ISSUE THREAD

**Issue by chriza** [pdir/maklermodul-bundle#22]
## Bug description
Nach Installation der Extension Maklermodul ist die Funktionalität des Quelltexteditors beschädigt.

## Steps to reproduce
Contao installieren -> Quelltexteditor prüfen, Maklermodul installieren -> Quelltexteditor prüfen

## Screenshots
![grafik](https://user-images.githubusercontent.com/1572887/113039578-1ba84080-9198-11eb-99a2-6d9a2eaf849a.png)

![grafik](https://user-images.githubusercontent.com/1572887/113039650-311d6a80-9198-11eb-8ad0-0434f490ce60.png)

## Environment
Contao ^4.9.13, && ^4.11.2
PHP 7.4

**Comment by MDevster** [comment]
fixed in version 2.7.5
