### ISSUE TITLE
Contao-Installationstool lässt sich nicht mehr aufrufen - SCSS-Fehler maklermodul_backend.scss

### ISSUE THREAD

**Issue by green-pixelbox** [pdir/maklermodul-bundle#23]
## Bug description
Nach der Installation des Maklermoduls im Contao-Manager lässt sich das Installtool nicht mehr aufrufen. Ich habe in der Contao Log-Datei nachgeschaut. Dort erscheint folgende Fehlermeldung:
complex selectors may not be extended.: maklermodul_backend.scss on line 138, at column 7 at /usr/www/users/variar/contao49/vendor/scssphp/scssphp/src/Compiler.php:5960
Dann habe ich in der Datei im Vendorordner die Datei maklermodul_backend.scss on line 138 auskommentiert, danach läuft auch das Contao-Installtool wieder. 

## Environment
Contao Version 4.9.14
Contao Manager Version 1.4.4
PHP 7.4
Makler Modulversion 2.7.6

**Comment by MDevster** [comment]
fixed in version 2.7.7
