### ISSUE TITLE
Fehlermeldung nach Aufruf der Schaltfläche/Button "Index aufbauen" im Contao Backend

### ISSUE THREAD

**Issue by martin-netprofit** [pdir/maklermodul-bundle#24]
## Bug description

Der Fehler erscheint im Contao Backend, wenn die Schaltfläche "Index aufbauen" betätigt wird.

Fehlermeldung: Attempted to call an undefined method named "getEmailBody" of class "Pdir\MaklermodulSyncBundle\Module\Sync".

## Screenshots

![Bildschirmfoto 2021-05-25 um 15 26 32](https://user-images.githubusercontent.com/25613502/119506499-41a02a80-bd6e-11eb-88ea-d400b346a496.jpg)

## Environment

Contao: Version 4.10.7
Maklermodul für Immobilienmakler: Version 2.7.7 
Maklermodul Sync: Version 2.5.0
PHP: 7.4.18

Hat das Problem sonst noch jemand?

**Comment by peerlight** [comment]
yes, same problem here; Backend does not load at PDIR APPS > Makler after update 2.6.4/5 -> 2.7.7

Contao: Version 4.9.9
Maklermodul für Immobilienmakler: Version 2.7.7
Maklermodul Sync: Version 2.5.3
PHP: 7.3.x

after clearing prod_cache backend loads with PDIR APPS > Makler but "Index aufbauen" triggers error again

**Comment by peerlight** [comment]
Fehler verschwindet nach Maklermodul Sync: Version 2.5.3 -> 2.6.3
