### ISSUE TITLE
Problem beim Laden der Bilder in der Listenansicht

### ISSUE THREAD

**Issue by avoca77** [pdir/maklermodul-bundle#25]
## Bug description
Beim Aufruf der Seite mit der Listenansicht wird das letzte untere Bild der Liste ganz kurz an oberster Stelle über die gesamte verfügbare Breite angezeigt, bevor die Bilder der Liste in vorgesehener Größe angezeigt werden. Manchmal bleibt die Listenansicht auch "hängen" und alle Bilder werden über die gesamte Breite angezeigt. Nach erneutem Laden wird die Liste dann angezeigt. Dieses Problem kann ich auch auf diesen Demoseiten reproduzieren:

https://www.freie-immo.com/haus-verkaufen-dresden.html

https://mate.pdir.de/immobilien.html

Anscheinend braucht das Script eine Weile, bis die Listenansicht geladen ist. Gibt es eine Möglichkeit, dieses Verhalten in der Listenansicht zu unterbinden? 

## Environment
Contao Version 4.9.14
Contao Manager Version 1.4.4
PHP 7.4
Makler Modulversion 2.7.6
Mate Theme

**Comment by MDevster** [comment]
Hi @avoca77 kannst du mal bitte prüfen ob das Laden der Listenansicht nun besser funktioniert?

**Comment by MDevster** [comment]
Closed because there was no more feedback. You are welcome to reopen the ticket.

**Comment by avoca77** [comment]
Hi @MDevster, dein Link führt auf eine 404. Ich habe aber auf diesen beiden Websites noch mal geschaut und konnten den Fehler nicht mehr reproduzieren. Da sieht alles perfekt aus.

https://www.freie-immo.com/haus-verkaufen-dresden.html

https://mate.pdir.de/immobilien.html
