### ISSUE TITLE
Immobilienscout24-Import-Link im Backend nicht vorhanden

### ISSUE THREAD

**Issue by green-pixelbox** [pdir/maklermodul-bundle#26]
Leider kann man den Immobilienscout24-Import im Contao-Backend nicht konfigurieren. In Ihrer Beschreibung steht, das man im Backend bei PDIR APPS auf Immoblienscout24 Import klicken soll und die Daten von Immo dort eingeben muss (siehe Anhang Screenshot maklermodul2). LEider kann ich im Backend keinen Link / Option dazu finden, wo man das eintragen kann (siehe Anhang Screenshot maklermodul1).
Contao-Version: 4.9.16
Maklermodul für Immobilienmakler Version: 2.7.7
pdir/maklermodul-sync-bundle-zip Version: 2.5
![maklermodul1](https://user-images.githubusercontent.com/3920742/125097581-91e10b00-e0d6-11eb-9f37-446b2826637c.PNG)
![maklermodul2](https://user-images.githubusercontent.com/3920742/125097583-9279a180-e0d6-11eb-8b0c-5976bd0fb381.PNG)

**Comment by MDevster** [comment]
Hallo Peter, es sieht so aus als wäre nur der Fahrzeugmanager (mobilede-bundle) installiert, du kannst mir gern an support@pdir.de einen Contoa Admin Zugang, Manager Passwort und Install-Tool Passwort senden, dann schauen wir wo das Problem ist.
