### ISSUE TITLE
Version 2.53 - Deletion of objects not working

### ISSUE THREAD

**Issue by olivergrosche** [pdir/maklermodul-bundle#27]
## Bug description
when sending the delete command from the real estate software, it sends a zip-file to the upload-folder,
but nothing happens, the object stays in place

## Environment
contao 4.9.16 with maklermodul 2.5.3

**Comment by MDevster** [comment]
Please update to latest version 2.7.7.

**Comment by olivergrosche** [comment]
ok, when updating, do i have to update the makle-modul-sync aswell?

**Comment by MDevster** [comment]
yes

**Comment by olivergrosche** [comment]
which version is it (maklermodul-sync)?
when i try to update to 2.7.7, it stays on 2.5.3

**Comment by MDevster** [comment]
Please use maklermodul-sync ^2.6, latest version is 2.6.2

**Comment by olivergrosche** [comment]
Thanks much! Everything is working fine!

**Comment by MDevster** [comment]
Very nice!
