### ISSUE TITLE
Immobilienimport nicht möglich (manuell und auch nicht via Schnittstelle)

### ISSUE THREAD

**Issue by avoca77** [pdir/maklermodul-bundle#28]
## Bug description
Nach dem manuellen Import der Objekte erhalte ich folgende Fehlermeldung (Kunde kann auch keine Objekte via Schnittstelle übertragen):
"Internal Server Error Was ist das Problem? Call to a member function __toString() on null"

Die Meldung in der Log-Datei sieht dann wie folgt aus:
`[2021-09-07 16:58:52] request.INFO: Matched route "contao_backend". {"route":"contao_backend","route_parameters":{"_route":"contao_backend","_scope":"backend","_token_check":true,"_controller":"Contao\\CoreBundle\\Controller\\BackendController::mainAction"},"request_uri":"https://xxxxx/contao?act=import&do=maklermodulSetup&ref=xxxxxxx","method":"GET"} []
[2021-09-07 16:58:52] request.CRITICAL: Uncaught PHP Exception Error: "Call to a member function __toString() on null" at /www/htdocs/xxxxx/xxxxx/website/c4.9/vendor/pdir/maklermodul-sync-bundle/src/Classes/Domain/Model/ImportTarget.php line 318 {"exception":"[object] (Error(code: 0): Call to a member function __toString() on null at /www/htdocs/xxxxx/xxxxx/website/c4.9/vendor/pdir/maklermodul-sync-bundle/src/Classes/Domain/Model/ImportTarget.php:318)"} []
`
Das Problem trat schon mal auf, könnte es dasselbe Problem sein? [https://github.com/pdir/maklermodul-bundle/issues/21](url)

## Environment
Contao 4.9.20
maklermodul-bundle: 2.7.7
maklermodul-sync-bundle: 2.6.2
PHP 7.4.19

**Comment by MDevster** [comment]
Please update to maklermodul-bundle: 2.8.0 and maklermodul-sync-bundle: 2.7.0

**Comment by avoca77** [comment]
Leider ist ein Update via Manager nicht möglich.
Folgende Fehlermeldung wird ausgegeben:
`CRITICAL [console] Error thrown while running command "cache:warmup --env=prod --no-ansi". Message: "Class 'Contao\ArrayUtil' not found" ["exception" => Error { …},"command" => "cache:warmup --env=prod --no-ansi","message" => "Class 'Contao\ArrayUtil' not found"]
In config.php line 34:
Attempted to load class "ArrayUtil" from namespace "Contao".
Did you forget a "use" statement for "ContaoBootstrap\Core\Util\ArrayUtil"?
cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--] <command>
Script Contao\ManagerBundle\Composer\ScriptHandler::initializeApplication handling the post-install-cmd event terminated with an exception
In ScriptHandler.php line 97:
An error occurred while executing the "cache:warmup" command: 14:20:31 CRIT
ICAL [console] Error thrown while running command "cache:warmup --env=prod
--no-ansi". Message: "Class 'Contao\ArrayUtil' not found" ["exception" =>
Error { …},"command" => "cache:warmup --env=prod --no-ansi","message" => "C
lass 'Contao\ArrayUtil' not found"]
In config.php line 34:
Attempted to load class "ArrayUtil" from namespace "Contao".
Did you forget a "use" statement for "ContaoBootstrap\Core\Util\ArrayUtil
"?
cache:warmup [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--
verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--en
v ENV] [--] <command>
install [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>...]
# Process terminated with exit code 1
# Result: General error`

**Comment by avoca77** [comment]
Environment

Contao 4.9.34
maklermodul-bundle: 2.7.9
maklermodul-sync-bundle: 2.6.3
PHP 7.4.30
