### ISSUE TITLE
Notice: Undefined index: @gruppe while importing with APP_ENV=dev

### ISSUE THREAD

**Issue by ff1601com** [pdir/maklermodul-bundle#32]
## Bug description
If a user starts the import-command via: 
- `php vendor/bin/contao-console maklermodul:import ` 

while being in dev-environment the user gets the following error message:

```
20:58:18 CRITICAL  [console] Error thrown while running command "maklermodul:import --debug". Message: "Notice: Undefined index: @gruppe" ["exception" => ErrorException { …},"command" => "maklermodul:import --debug","message" => "No
tice: Undefined index: @gruppe"]

In ImportTarget.php line 279:

  Notice: Undefined index: @gruppe  


maklermodul:import [--debug]
```

## Steps to reproduce
- Create .env - file in the system
  - set "APP_ENV" to "dev"
  - `APP_ENV=dev`

- Go to console or to the backend and trigger the import-command:
  - Backend via Button
  - Console: `php vendor/bin/contao-console maklermodul:import ` 

## Expected behavior
The import command should not throw errors/notices even when in dev-environment.

## Environment
- PHP-Version: 7.4.30
- Contao-Version: 4.13.14
- Bundles:
  - pdir/maklermodul-bundle: 2.8.2
  - pdir/maklermodul-sync-bundle: 2.7.2

**Comment by MDevster** [comment]
Fixed in version 2.7.4 of maklermodul-sync-bundle.
