### ISSUE TITLE
Bug in filter translation

### ISSUE THREAD

**Issue by agonyz** [pdir/maklermodul-bundle#34]
## Bug description
In the filter translation the name is set to a boolean instead of the translation value. 

It works for translations that are purely uppercase eg. ```KAUFEN``` because the value gets set again in Line ```348``` but does not for mixed eg. ```MIETE_PACHTEN```.

This bug can be fixed by using the ```Null Coalescing Operator```.

## Steps to reproduce
Install the bundle, use the filter and have a translation that is not purely uppercase.

## Expected behavior
The  filter should output the translation from the translation files.

#### Frontend output of filter button shows "1" should be "Mieten/Pachten"
![image](https://user-images.githubusercontent.com/71080150/208965388-daec4af3-d605-4c23-9e26-4b8c964d703b.png)

#### Debugging with Symfony Profiler
![image](https://user-images.githubusercontent.com/71080150/208965547-96f34398-af3c-4248-8a7b-5f4266ec6c09.png)

## Environment
- PHP-Version: 7.4.30
- Contao-Version: 4.13.14
- Bundles:
  - pdir/maklermodul-bundle: 2.8.2
  - pdir/maklermodul-sync-bundle: 2.7.2

##

This bug can be fixed by my pull-request: https://github.com/pdir/maklermodul-bundle/pull/33

**Comment by seibtph** [comment]
Thanks for the PR. Version 2.8.3 is published.
