### ISSUE TITLE
Pfade in der Dokumentation

### ISSUE THREAD

**Issue by pedal123** [pdir/maklermodul-bundle#37]
Das Modul funktioniert bestens.  Sind die Pfade für den Poor-Man-Cron  in der Dokumentation eventuell nicht mehr aktuell? 
https://pdir.de/docs/de/contao/extensions/maklermodul/import/

<?php

$GLOBALS['TL_CRON']['hourly'][] = array('Pdir\MaklermodulSyncBundle\Module\Sync', 'estateImport');
$GLOBALS['TL_CRON']['hourly'][] = array('Pdir\MaklermodulSyncBundle\Module\Sync', 'estateIndex');

**Comment by seibtph** [comment]
Die Pfade sollten noch genauso funktionieren. Ich habe das gerade mal getestet. Funktioniert es nicht? Hast du auch den Cache im Contao Manager geleert?
