### ISSUE TITLE
Begrenzung der Dateien im files/maklermodul/org Ordner

### ISSUE THREAD

**Issue by pedal123** [pdir/maklermodul-bundle#38]
Es wäre schön die Anzahl der Dateien im org Ordner begrenzen zu können.
Ideal wäre eine Einstellung: x letzte Dateien behalten.

**Comment by MDevster** [comment]
Hallo @pedal123, du kannst verhindern das die Original Dateien abgelegt werden, in dem du die import.ini anpasst, siehe 
https://pdir.de/docs/de/contao/extensions/maklermodul/import/#hinweise

Dateiverwaltung -> maklermodul -> import.ini
`keep-source=false`

Oder wünschst du wirklich x letzte Importe sollen verfügbar bleiben? Wofür sollen die Dateien liegen bleiben?

**Comment by pedal123** [comment]
Vielen Dank, keep-source=false hatte ich übersehen.
Die Dateien sind hilfreich, um bei der Erstellung der Seite mit dem Kunden zu kommunizieren (Kunde lädt manuell hoch) und die Uploads oder cronjobs zu überwachen. Bei Problemen mit den Einträgen kann man einfach in die Dateien schauen ohne die sich schicken lassen zu müssen. Also im Normalbetrieb nicht notwendig, aber "wenn mal was ist" - schön zu haben.

Eine Frage, die im Zusammenhanghang mit den Cronjobs aufgetreten ist, was passiert bei mehreren Dateien im upload-Ordner?
Werden die nach Datum abgearbeitet? (Für den Fall, das zwischen den cronjobs mehrere Dateien hochgeladen werden)

**Comment by MDevster** [comment]
@pedal123 Ja, die Dateien werden anhand des Zeitstempels nacheinander importiert.
