### ISSUE TITLE
display:none is ignored by Safari on iOS

### ISSUE THREAD

**Issue by itcbchris** [pdir/maklermodul-bundle#9]
Safari Browser on iOS seems to ignore if: "display:none" is set to <option> elements.

Should be tested with, hidden attribute, as mentioned here:

https://stackoverflow.com/questions/45078722/jquery-hide-select-doesnt-work-in-safari

https://www.w3schools.com/tags/att_global_hidden.asp

**Comment by MDevster** [comment]
fixed in version 2.5.3

**Comment by UzyOrg** [comment]
I have the same issue, right now, the display  none works but not for a h2 tag
